### ISSUE TITLE
Problem with presentation slides

### ISSUE THREAD

**Issue by edwinlin** [learn-co-curriculum/campus-reference-materials#1]
Presentation slides do not give access to materials. Gets "You do not have access to this lesson."

**Comment by maxwellbenton** [comment]
Hi @edwinlin,

Thank you for spotting this and providing feedback. This lesson is actually deprecated and the content in the presentation slides is no longer accurate. 

We've removed the links to these slides to prevent confusion in case this lesson is deployed and will be removing this lesson from our Curriculum in an update in the next couple of weeks. We apologize for any confusion this may have caused.
