### ISSUE TITLE
Presentation Slides Inaccessible

### ISSUE THREAD

**Issue by skel11417** [learn-co-curriculum/campus-reference-materials#2]
When clicking on any of the links under Presentation Slides I get an alert "You Do Not Have Access to this Lesson"

**Comment by maxwellbenton** [comment]
Hi @skel11417,

Thank you for spotting this and providing feedback. This lesson is actually deprecated and the content in the presentation slides is no longer accurate. 

We've removed the links to these slides to prevent confusion in case this lesson is deployed and will be removing this lesson from our Curriculum in an update in the next couple of weeks. We apologize for any confusion this may have caused.
